name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build
      - name: Package metadata
        run: cargo package --no-verify
